#!/bin/bash


#http://stackoverflow.com/questions/8653126/how-to-increment-version-number-in-a-shell-script
increment_version ()
{
  declare -a part=( ${1//\./ } )
  declare    new
  declare -i carry=1

  for (( CNTR=${#part[@]}-1; CNTR>=0; CNTR-=1 )); do
    len=${#part[CNTR]}
    new=$((part[CNTR]+carry))
    [ ${#new} -gt $len ] && carry=1 || carry=0
    [ $CNTR -gt 0 ] && part[CNTR]=${new: -len} || part[CNTR]=${new}
  done
  new="${part[*]}"
  echo -e "${new// /.}"
}


VERSION_FILE=movegenerator/version.h

if [ ! -f "${VERSION_FILE}" ]
then
	echo "ERROR: version file not found!"
    exit
fi

GIT_VERSION=$(git describe --abbrev=0 --tags)
CODE_VERSION=$(cat ${VERSION_FILE} | grep IMPLEMENTATION_VERSION | sed -E 's/^.*\"(.*)\".*/\1/')

if [ -n "$(echo ${CODE_VERSION} | grep SNAPSHOT)" ]
then
 echo "Committed SNAPSHOT version: ${CODE_VERSION}"
else
    if [ "${GIT_VERSION}" != "${CODE_VERSION}" ]
    then
		git tag -a ${CODE_VERSION} -m "Committing a new version ${CODE_VERSION}"
		echo "Committed a NEW version: ${CODE_VERSION}"
    fi
    
    NEW_VERSION=$(increment_version ${CODE_VERSION})
    sed -i -E "s/${CODE_VERSION}/${NEW_VERSION}-SNAPSHOT/" ${VERSION_FILE}
    git add ${VERSION_FILE}
    git commit -m "Creating a new development version: ${NEW_VERSION}-SNAPSHOT"
fi

